POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Meu Primeiro Video",
    "description": "Primeiro video no canal",
    "duration": 180
}

###
POST http://localhost:3333/videos


###
GET http://localhost:3333/videos?search=II
###
###
GET http://localhost:3333/videos
###
GET http://localhost:3333/videos/a760a070-c0d1-4238-8ee5-5eeb2c077fc0

###
PUT http://localhost:3333/videos/a760a070-c0d1-4238-8ee5-5eeb2c077fc0
Content-Type: application/json


###

DELETE http://localhost:3333/videos/0acdce83-7841-4633-87c3-9123163b91f9

