POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Meu Primeiro Video",
    "description": "Primeiro video no canal",
    "duration": 180
}

###
POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Meu Primeiro Video",
    "description": "Parte dois, aka segundo video do canal",
    "duration": 180
}
###
GET http://localhost:3333/videos?search=II
###
###
GET http://localhost:3333/videos
###
GET http://localhost:3333/videos/cb525bd0-92d8-462b-aee3-52abe33e8c0

###
PUT http://localhost:3333/videos/9d997437-777e-4b02-9601-b809f1907549
Content-Type: application/json

{
    "title": "Meu Segundo Video",
    "description": "Segundo video do canal",
    "duration": 190
}
###

DELETE http://localhost:3333/videos/44a950d9-8c59-4a15-94be-4162396914a8

